### ISSUE TITLE
Todo :  게시글/댓글/좋아요 도메인 기능 개발 - 신성섭

### ISSUE THREAD

**Issue by sinseongseop** [CapstoneDesignCau/Back-End#13]
### 🚩 관련사항
관련된 이슈번호 혹은 pr번호를 기록합니다.

### 📍 이슈 종류
TODO (일정 정리) 

### 💡 상세설명
게시글/댓글/좋아요 관련 도메인의 기능을 신성섭이 개발합니다.

### 📃 진행사항
- [ ] 게시글 도메인 기능
- [x]  댓글 도메인 기능
- [x] 좋아요 도메인 기능

### ⚙️ 기타사항
기타 참고사항을 적어주세요.

### 💡 예상 개발 기간
9주차까지 완성.( 11월 3일까지)
